service: LocalStackTesting

functions:
  Basic:
    handler: src/basic.run
    description: Log hello
    name: ${self:custom.stage}-${self:service}-Basic

provider:
  stackName: ${self:custom.stage}-${self:service}
  versionFunctions: false
  name: aws
  timeout: 200
  runtime: python3.9
  region: ${file(./config/${self:custom.stage}.yml):region}
  logRetentionInDays: 30
  iam:
    role:
      tags:
      name: ${self:custom.stage}-${self:service}
      statements:
        - Effect: Allow
          Action:
            - "s3:DeleteObject"
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - "s3:List*"
          Resource:
            - "*"

  deploymentBucket:
    name: ${file(./config/${self:custom.stage}.yml):deploy_bucket}
  environment: ${file(./config/${self:custom.stage}.yml):env_vars}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-localstack

custom:
  stage: ${opt:stage, 'dev'}
  pythonRequirements:
    usePoetry: true
  localstack:
    stages:
      local

package:
  patterns:
    - "!venv/**"
    - "!.git/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!docker/**"
    - "!node_modules/**"
    - "!__pychache__/**"
    - "!.pytest_cache/**"
    - "!zz_notes/**"
    - "!tests/**"
    - "!terraform/**"
    - "!test_json/**"
    - "!stubs/**"
    - "!lambda_layers/**"
  individually: true
