service: LocalStackTesting

provider:
  stackName: ${self:custom.stage}-${self:service}
  versionFunctions: false
  name: aws
  timeout: 200
  runtime: python3.9
  region: ${file(./config/${self:custom.stage}.yml):region}
  logRetentionInDays: 30
  iam:
    role:
      tags:
      name: ${self:custom.stage}-${self:service}
      statements:
        - Effect: Allow
          Action:
            - "s3:List*"
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - "s3:DeleteObject"
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - "DynamoDB:DeleteObject"
            - "DynamoDB:PutObject"
            - "DynamoDB:GetObject"
          Resource:
            - "*"

  deploymentBucket:
    name: ${file(./config/${self:custom.stage}.yml):deploy_bucket}
  environment: ${file(./config/${self:custom.stage}.yml):env_vars}

functions:
  Basic:
    handler: src/basic.run
    description: Log hello
    name: ${self:custom.stage}-${self:service}-Basic

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_table
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH

package:
  patterns:
    - "!venv/**"
    - "!.git/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!docker/**"
    - "!node_modules/**"
    - "!__pychache__/**"
    - "!.pytest_cache/**"
    - "!zz_notes/**"
    - "!tests/**"
    - "!terraform/**"
    - "!test_json/**"
    - "!stubs/**"
    - "!lambda_layers/**"
  individually: true

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-localstack
  - serverless-step-functions
  - serverless-dynamodb-local
  - serverless-create-global-dynamodb-table

custom:
  stage: ${opt:stage, 'dev'}
  pythonRequirements:
    dockerEnv:
      - https_proxy
    usePoetry: false
  localstack:
    stages:
      local
